FROM debian:buster
RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list

# Set environment variable to disable interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Build arguments with defaults
ARG WOLFSSL_VERSION=v5.8.0-stable
ARG COMMIT=v1.4.20-stable

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    autoconf \
    automake \
    libtool \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# Clone and build wolfSSL at WOLFSSL_VERSION
RUN git clone --depth 1 --branch ${WOLFSSL_VERSION} https://github.com/wolfSSL/wolfssl.git && \
    cd wolfssl && \
    ./autogen.sh && \
    ./configure --enable-wolfssh --enable-keygen --enable-shared && \
    make && make install && ldconfig

# Clone wolfSSH at COMMIT
RUN git clone --depth 1 --branch ${COMMIT} https://github.com/wolfSSL/wolfssh.git
    
# Copy echoserver.c to the wolfSSH examples directory
#COPY echoserver.c /opt/wolfssh/examples/echoserver/echoserver.c

# Build wolfSSH
RUN cd wolfssh && \
    ./autogen.sh && \
    ./configure --enable-shell --enable-sshd && \
    make && make install && ldconfig

RUN printf 'Port 11111\nPermitRootLogin yes\n' > /opt/wolfssh/sshd_config

RUN useradd -m sshd && echo "sshd:sshd" | chpasswd
RUN useradd -m testuser && echo "testuser:root" | chpasswd

EXPOSE 11111

WORKDIR /opt/wolfssh


CMD ["./apps/wolfsshd/wolfsshd", "-D", "-f", "sshd_config", "-h", "keys/gretel-key-ecc.pem", "-p", "11111"]