FROM debian:buster

RUN apt-get update -y && \
    apt-get install -y openssh-server openssh-client && \
    mkdir /var/run/sshd

RUN ssh-keygen -A

RUN useradd -m -s /bin/bash testuser && \
    echo "testuser:root" | chpasswd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]